import { NextResponse } from "next/server";
import { DUSUN, IDM_DATA, IDM_INDIKATOR, IDM_HISTORI } from "@/lib/dummy";

export async function GET() {
  // cluster6 → Indikator IDM per dimensi (dipakai tab Indeks/Peta untuk rekap)
  const allIndikator = [
    ...IDM_INDIKATOR.sosial.map((ind, j) => ({
      id: `IDM-S-${j}`,
      kode_reg: `S-${j + 1}`,
      sektor: "Sosial",
      sub_sektor: ind.nama,
      sub_klaster: "Dimensi Sosial",
      kewenangan: "Desa",
      kabupaten_kota: "Batanghari",
      kecamatan: "Maro Sebo Ulu",
      desa: "Remau Bako Tuo",
      alamat_lengkap: "Desa Remau Bako Tuo, Kec. Maro Sebo Ulu",
      status_layanan: ind.skor >= 0.75 ? "Baik" : "Sedang",
      status_fisik: ind.skor >= 0.75 ? "Baik" : "Perlu Peningkatan",
      // status_kerusakan dipakai JS untuk kpi-kuning/biru/abu/putih (tab Indeks)
      status_kerusakan: ind.skor >= 0.80 ? "kuning" : ind.skor >= 0.70 ? "biru" : "biru_keabuan",
      kondisi: ind.skor >= 0.75 ? "Baik" : "Sedang",
      lat: DUSUN[j % DUSUN.length].lat,
      lng: DUSUN[j % DUSUN.length].lng,
      nilai_kerusakan_ringan: Math.round(ind.skor * 100),
      nilai_kerusakan_sedang: 0,
      nilai_kerusakan_berat: 0,
      nilai_kerusakan: Math.round(ind.skor * 100),
      nilai_kerugian: 0,
      total_kerusakan_kerugian: Math.round(ind.skor * 100),
      estimasi_biaya_rehab: 0,
      keterangan: `Skor IDM Dimensi Sosial – ${ind.nama}: ${ind.skor.toFixed(4)}`,
      link_maps: `https://www.google.com/maps?q=${DUSUN[j % DUSUN.length].lat},${DUSUN[j % DUSUN.length].lng}`,
      status: ind.skor >= 0.80 ? "kuning" : ind.skor >= 0.70 ? "biru" : "biru_keabuan",
      satuan: "Skor",
      volume: 1,
      skor_idm: ind.skor,
      nama_indikator: ind.nama,
      dimensi: "Sosial",
    })),
    ...IDM_INDIKATOR.ekonomi.map((ind, j) => ({
      id: `IDM-E-${j}`,
      kode_reg: `E-${j + 1}`,
      sektor: "Ekonomi",
      sub_sektor: ind.nama,
      sub_klaster: "Dimensi Ekonomi",
      kewenangan: "Desa",
      kabupaten_kota: "Batanghari",
      kecamatan: "Maro Sebo Ulu",
      desa: "Remau Bako Tuo",
      alamat_lengkap: "Desa Remau Bako Tuo, Kec. Maro Sebo Ulu",
      status_layanan: ind.skor >= 0.70 ? "Baik" : "Sedang",
      status_fisik: "Perlu Peningkatan",
      status_kerusakan: ind.skor >= 0.70 ? "biru" : "biru_keabuan",
      kondisi: "Sedang",
      lat: DUSUN[j % DUSUN.length].lat,
      lng: DUSUN[j % DUSUN.length].lng,
      nilai_kerusakan_ringan: Math.round(ind.skor * 100),
      nilai_kerusakan_sedang: 0,
      nilai_kerusakan_berat: 0,
      nilai_kerusakan: Math.round(ind.skor * 100),
      nilai_kerugian: 0,
      total_kerusakan_kerugian: Math.round(ind.skor * 100),
      estimasi_biaya_rehab: 0,
      keterangan: `Skor IDM Dimensi Ekonomi – ${ind.nama}: ${ind.skor.toFixed(4)}`,
      link_maps: `https://www.google.com/maps?q=${DUSUN[j % DUSUN.length].lat},${DUSUN[j % DUSUN.length].lng}`,
      status: ind.skor >= 0.70 ? "biru" : "biru_keabuan",
      satuan: "Skor",
      volume: 1,
      skor_idm: ind.skor,
      nama_indikator: ind.nama,
      dimensi: "Ekonomi",
    })),
    ...IDM_INDIKATOR.lingkungan.map((ind, j) => ({
      id: `IDM-L-${j}`,
      kode_reg: `L-${j + 1}`,
      sektor: "Lingkungan",
      sub_sektor: ind.nama,
      sub_klaster: "Dimensi Lingkungan",
      kewenangan: "Desa",
      kabupaten_kota: "Batanghari",
      kecamatan: "Maro Sebo Ulu",
      desa: "Remau Bako Tuo",
      alamat_lengkap: "Desa Remau Bako Tuo, Kec. Maro Sebo Ulu",
      status_layanan: "Baik",
      status_fisik: "Baik",
      status_kerusakan: "kuning",
      kondisi: "Baik",
      lat: DUSUN[j % DUSUN.length].lat,
      lng: DUSUN[j % DUSUN.length].lng,
      nilai_kerusakan_ringan: Math.round(ind.skor * 100),
      nilai_kerusakan_sedang: 0,
      nilai_kerusakan_berat: 0,
      nilai_kerusakan: Math.round(ind.skor * 100),
      nilai_kerugian: 0,
      total_kerusakan_kerugian: Math.round(ind.skor * 100),
      estimasi_biaya_rehab: 0,
      keterangan: `Skor IDM Dimensi Lingkungan – ${ind.nama}: ${ind.skor.toFixed(4)}`,
      link_maps: `https://www.google.com/maps?q=${DUSUN[j % DUSUN.length].lat},${DUSUN[j % DUSUN.length].lng}`,
      status: "kuning",
      satuan: "Skor",
      volume: 1,
      skor_idm: ind.skor,
      nama_indikator: ind.nama,
      dimensi: "Lingkungan",
    })),
  ];

  // cluster1 → Histori IDM per tahun (dipakai peta untuk dot)
  const cluster1 = IDM_HISTORI.map((h, i) => ({
    id: `IDM-H-${h.tahun}`,
    kabupaten_kota: "Batanghari",
    lat: IDM_DATA ? -1.2182621315578288 + (i * 0.001) : -1.2182621315578288,
    lng: 104.35172172755148,
    tahun: h.tahun,
    skor: h.skor,
    status: h.status,
    korban_meninggal: 0,
    korban_luka: 0,
    pengungsi: 0,
    rumah_rb: 0,
    rumah_rs: 0,
    rumah_rr: 0,
    nama_indikator: `IDM ${h.tahun}`,
    keterangan: `Skor IDM ${h.tahun}: ${h.skor}`,
  }));

  return NextResponse.json({
    cluster6: allIndikator,
    cluster1,
    cluster6Icons: allIndikator,
    total: allIndikator.length,
    idm_summary: IDM_DATA,
  });
}
